### ISSUE TITLE
Mac OSX Unicode parsing error

### ISSUE THREAD

**Issue by ccsplit** [eerohele/sublime-lxml#5]
Currently with the Mac OSX build of sublime-lxml for ST3 build 3103 I am receiving the following error when attempting to `set syntax: XML` for any xml files: `Unicode parsing is not supported on this platform`. From information @keith-hall has [found](https://groups.google.com/forum/#!topic/beautifulsoup/68CG0m-6tv8) and also from [lxml](http://lxml.de/build.html#building-lxml-on-macos-x) it appears that lxml has to be built with `STATIC_DEPS=true` otherwise it will use the Mac OSX version which appears to fail. I have attempted to place a built version of lxml instead of the `st3_osx_64` lxml version but this appears to fail as I'm not sure how these are built. 

Even a simple example such as the following fails:

```
<xml>
  <node>text</node>
</xml>
```

More information can be found on [Sublime-xpath#22](https://github.com/rosshadden/sublime-xpath/issues/22).

**Comment by eerohele** [comment]
Thanks for the report. I do have a Mac and I can reproduce the error mentioned in the other thread.

However, the current version of `st3_osx_64` _is_ statically built — otherwise it wouldn't work at all. But the lxml dependency does work with [my plugin](https://github.com/eerohele/exalt), for instance. I'm probably just doing something differently than the sublime-xpath plugin.

Can you try copy-pasting this into your Sublime Text console?

``` python
from lxml import etree; import io; etree.tostring(etree.parse(io.BytesIO(bytes('<xml><node>text</node></xml>', 'UTF-8'))))
```

It lxml is able to parse it, it should return:

```
b'<xml><node>text</node></xml>'
```

Which would indicate that the dependency itself works — even if not 100%.

Note that the code snippet above first converts the XML string into bytes, which [I found was necessary](https://github.com/eerohele/exalt/blob/852d4b02ead6db3cfdaf0c1a732fc64eaeb71322/utils.py#L20-L34) to reliably parse the contents of a Sublime Text view regardless of the encoding set in the XML declaration. I don't know whether that affects this particular issue, though. Probably not.

I didn't have the time to look through the Google Groups thread you provided yet, though, so there might be something there that helps us. I'll be away for the next couple of days, though, so I probably won't have the time to look into it before the start of next week.

**Comment by keith-hall** [comment]
@eerohele thanks for the info about converting the XML string (retrieved from the view) into bytes - I believe I can change the xpath plugin to also do this, which will mean that you won't need to make any changes in this repo :) :+1:

**Comment by ccsplit** [comment]
@eerohele that worked as expected and if @keith-hall remedies it in that way then it should resolve the issue. Thanks for your prompt response.

**Comment by ccsplit** [comment]
@eerohele closing this issue as @keith-hall remedied the issue using your workaround. Thanks again.

**Comment by eerohele** [comment]
Glad to hear y'all were able to find a solution!
